version: '3.8'

services:
  # Redis Service
  redis:
    image: redis:latest
    container_name: Redis
    restart: always
    network_mode: "host"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Zookeeper Service
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: Zookeeper
    restart: always
    network_mode: "host"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Store Service
  store-service:
    build: ./src/storeService
    container_name: StoreService
    restart: always
    network_mode: "host"
    environment:
      STORE_SERVICE_PORT: 3000
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      DATABASE_URL: "postgresql://postgres:Sultanpur12@rds-postgres-ec2-graphql-server.crqiamkkkwdr.ap-south-1.rds.amazonaws.com/postgres?schema=public"
      NODE_ENV: development
      LOG_LEVEL: info
      STORE_SERVICE_URL: http://localhost:3000
    depends_on:
      - redis

  # Executor Service
  executor-service:
    build: ./src/executionService
    container_name: ExecutorService
    restart: always
    network_mode: "host"
    environment:
      ZOOKEEPER_HOST: localhost:2181
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      DATABASE_URL: "postgresql://postgres:Sultanpur12@rds-postgres-ec2-graphql-server.crqiamkkkwdr.ap-south-1.rds.amazonaws.com/postgres?schema=public"
      NODE_ENV: development
    depends_on:
      - zookeeper
      - redis
      - store-service

  # Scheduler Service
  scheduler-service:
    build: ./src/schedulerService
    container_name: SchedulerService
    restart: always
    network_mode: "host"
    environment:
      ZOOKEEPER_HOST: localhost:2181
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      DATABASE_URL: "postgresql://postgres:Sultanpur12@rds-postgres-ec2-graphql-server.crqiamkkkwdr.ap-south-1.rds.amazonaws.com/postgres?schema=public"
      NODE_ENV: development
    depends_on:
      - zookeeper
      - redis
      - store-service

volumes:
  postgres_data:
  redis_data:
