version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: Postgres
    restart: always
    network_mode: "host"
    environment:
      POSTGRES_USER: akash
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: myPostgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: Redis
    restart: always
    network_mode: "host"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: Zookeeper
    restart: always
    network_mode: "host"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

volumes:
  postgres_data:
  redis_data:
